### ISSUE TITLE
Production readiness

### ISSUE THREAD

**Issue by gsogol** [Elders/Hystrix.NET#1]
Is anyone using it in production? And does this plug into the hystrix dashboard? Thank you

**Comment by sdluxeon** [comment]
Hey,
Right know we are using it in production. And yes it works with the both the hystrix dashboard and the original java Turbine. We also have support for sending stats to Atlas. Currently we are rewriting the dashboard to work with Owin Selfhost so that you could use it with just a nuget package. However you should know that is 2 years behind the official Netflix repo and it also misses several key features like the collapsers for example. We picked this up form here -> https://hystrixnet.codeplex.com/SourceControl/latest 
and we started working on this by fixing bugs, memory leaks etc just trying to put out a stable version. For know it looks stable and there are not unexpected issues and we intened to keep on developing it, adding feautres, optimisations etc.

**Comment by gsogol** [comment]
When you say rewriting the dashboard, which one? Are you not sending it to the hystrix one via SSE?

**Comment by sdluxeon** [comment]
This one => https://github.com/Elders/Hystrix.NET/tree/master/src/Hystrix.Dashboard
But its working with the old ashx handlers. We have reworked it to use Owin Middleware, just have to build the static files as embeded resource in the assembly and make the owin static file server work with them. Just like Thinktectures Idenetity Server.

**Comment by gsogol** [comment]
So you created your own and not using hystrix dashboard? Just trying to connect the dots

**Comment by sdluxeon** [comment]
Yes and no. This dashboard came from the guy who started porting the original [Java Project](https://github.com/Netflix/Hystrix)  and now we are rewriting it to be used with Owin Katana. The idea is to have the dashboard self hosted wherever you use hystrix. Btw there is no reason for the .net implementation not to work with the java dashboard as it already works with [Turbine](https://github.com/Netflix/Turbine).

**Comment by gsogol** [comment]
I guess I don't get there point of having another dashboard? Would you want to utilize hundreds of developers already working on the Netflix dashboard and concentrate on collapsers, etc?

**Comment by mynkow** [comment]
We are in prodiction since 1st of Sept

**Comment by mynkow** [comment]
Dasboard https://github.com/Elders/Hystrix.NET.Dashboard
